use std::collections::HashMap;

use crate::env_store::EnvSnapshot;
use crate::error::EnvarlyError;

/// Export snapshot as pretty-printed JSON.
/// scope: "User" | "System" | "All"
pub fn to_json(snapshot: &EnvSnapshot, scope: &str) -> String {
    let mut obj = serde_json::Map::new();
    if scope != "System" {
        obj.insert(
            "user".into(),
            serde_json::to_value(&snapshot.user).unwrap_or_default(),
        );
    }
    if scope != "User" {
        obj.insert(
            "system".into(),
            serde_json::to_value(&snapshot.system).unwrap_or_default(),
        );
    }
    serde_json::to_string_pretty(&serde_json::Value::Object(obj)).unwrap_or_default()
}

/// Export snapshot in Windows Registry .reg format.
/// scope: "User" | "System" | "All"
pub fn to_reg(snapshot: &EnvSnapshot, scope: &str) -> String {
    let mut out = String::from("Windows Registry Editor Version 5.00\r\n");
    if scope != "System" {
        out.push_str("\r\n[HKEY_CURRENT_USER\\Environment]\r\n");
        let mut pairs: Vec<_> = snapshot.user.iter().collect();
        pairs.sort_by_key(|(k, _)| k.to_lowercase());
        for (k, v) in pairs {
            out.push_str(&format!("\"{}\"=\"{}\"\r\n", reg_escape(k), reg_escape(v)));
        }
    }
    if scope != "User" {
        out.push_str(
            "\r\n[HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment]\r\n",
        );
        let mut pairs: Vec<_> = snapshot.system.iter().collect();
        pairs.sort_by_key(|(k, _)| k.to_lowercase());
        for (k, v) in pairs {
            out.push_str(&format!("\"{}\"=\"{}\"\r\n", reg_escape(k), reg_escape(v)));
        }
    }
    out
}

// ── PowerShell script ─────────────────────────────────────────────────────

/// Export snapshot as a PowerShell script that sets environment variables.
pub fn to_ps1(snapshot: &EnvSnapshot, scope: &str) -> String {
    let mut out = String::from("# Generated by Envarly\n");
    if scope != "System" && !snapshot.user.is_empty() {
        out.push_str("\n# User environment variables\n");
        let mut pairs: Vec<_> = snapshot.user.iter().collect();
        pairs.sort_by_key(|(k, _)| k.to_lowercase());
        for (k, v) in pairs {
            out.push_str(&format!(
                "[Environment]::SetEnvironmentVariable({}, {}, 'User')\n",
                ps1_quote(k),
                ps1_quote(v),
            ));
        }
    }
    if scope != "User" && !snapshot.system.is_empty() {
        out.push_str("\n# System environment variables\n");
        let mut pairs: Vec<_> = snapshot.system.iter().collect();
        pairs.sort_by_key(|(k, _)| k.to_lowercase());
        for (k, v) in pairs {
            out.push_str(&format!(
                "[Environment]::SetEnvironmentVariable({}, {}, 'Machine')\n",
                ps1_quote(k),
                ps1_quote(v),
            ));
        }
    }
    out
}

// ── PowerShell DSC v2 ─────────────────────────────────────────────────────

/// Export snapshot as a PowerShell DSC v2 Configuration (.ps1).
pub fn to_dsc_v2(snapshot: &EnvSnapshot, scope: &str) -> String {
    let mut resources = String::new();
    if scope != "System" {
        let mut pairs: Vec<_> = snapshot.user.iter().collect();
        pairs.sort_by_key(|(k, _)| k.to_lowercase());
        for (k, v) in pairs {
            resources.push_str(&format!(
                "        Environment {} {{\n            Name   = {}\n            Value  = {}\n            Target = @('User')\n        }}\n",
                dsc_id(k, "User"),
                ps1_quote(k),
                ps1_quote(v),
            ));
        }
    }
    if scope != "User" {
        let mut pairs: Vec<_> = snapshot.system.iter().collect();
        pairs.sort_by_key(|(k, _)| k.to_lowercase());
        for (k, v) in pairs {
            resources.push_str(&format!(
                "        Environment {} {{\n            Name   = {}\n            Value  = {}\n            Target = @('Machine')\n        }}\n",
                dsc_id(k, "Machine"),
                ps1_quote(k),
                ps1_quote(v),
            ));
        }
    }
    format!(
        "# Generated by Envarly\nConfiguration EnvarlyConfig {{\n    Import-DscResource -ModuleName PSDscResources\n\n    Node localhost {{\n{}    }}\n}}\nEnvarlyConfig\n",
        resources,
    )
}

// ── PowerShell DSC v3 ─────────────────────────────────────────────────────

/// Export snapshot as a DSC v3 config document (.dsc.yaml).
pub fn to_dsc_v3(snapshot: &EnvSnapshot, scope: &str) -> String {
    let mut resources = String::new();
    if scope != "System" {
        let mut pairs: Vec<_> = snapshot.user.iter().collect();
        pairs.sort_by_key(|(k, _)| k.to_lowercase());
        for (k, v) in pairs {
            resources.push_str(&format!(
                "  - name: Set {} (User)\n    type: Microsoft.Windows/Environment\n    properties:\n      name: {}\n      value: {}\n      scope: CurrentUser\n",
                k,
                yaml_quote(k),
                yaml_quote(v),
            ));
        }
    }
    if scope != "User" {
        let mut pairs: Vec<_> = snapshot.system.iter().collect();
        pairs.sort_by_key(|(k, _)| k.to_lowercase());
        for (k, v) in pairs {
            resources.push_str(&format!(
                "  - name: Set {} (System)\n    type: Microsoft.Windows/Environment\n    properties:\n      name: {}\n      value: {}\n      scope: LocalMachine\n",
                k,
                yaml_quote(k),
                yaml_quote(v),
            ));
        }
    }
    format!(
        "# Generated by Envarly\n# Requires: DSC v3 (https://github.com/PowerShell/DSC)\n$schema: https://aka.ms/DSC/2023/08/config\nresources:\n{}",
        resources,
    )
}

// ── Ansible ───────────────────────────────────────────────────────────────

/// Export snapshot as an Ansible playbook (.yml).
pub fn to_ansible(snapshot: &EnvSnapshot, scope: &str) -> String {
    let mut tasks = String::new();
    if scope != "System" {
        let mut pairs: Vec<_> = snapshot.user.iter().collect();
        pairs.sort_by_key(|(k, _)| k.to_lowercase());
        for (k, v) in pairs {
            tasks.push_str(&format!(
                "    - name: Set {} (User)\n      ansible.windows.win_environment:\n        name: {}\n        value: {}\n        level: user\n        state: present\n\n",
                k,
                yaml_quote(k),
                yaml_quote(v),
            ));
        }
    }
    if scope != "User" {
        let mut pairs: Vec<_> = snapshot.system.iter().collect();
        pairs.sort_by_key(|(k, _)| k.to_lowercase());
        for (k, v) in pairs {
            tasks.push_str(&format!(
                "    - name: Set {} (System)\n      ansible.windows.win_environment:\n        name: {}\n        value: {}\n        level: machine\n        state: present\n\n",
                k,
                yaml_quote(k),
                yaml_quote(v),
            ));
        }
    }
    format!(
        "# Generated by Envarly\n---\n- name: Configure environment variables\n  hosts: windows\n  gather_facts: false\n  tasks:\n{}",
        tasks,
    )
}

// ── Helpers ───────────────────────────────────────────────────────────────

/// Single-quote a string for PowerShell. Single quotes prevent variable expansion.
/// Internal single quotes are escaped by doubling: ' → ''
fn ps1_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "''"))
}

/// Double-quote a string for YAML. Escapes backslashes, double quotes, and control chars.
fn yaml_quote(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t");
    format!("\"{}\"", escaped)
}

/// Sanitised identifier for a DSC v2 resource instance (alphanumeric + underscore, scope-prefixed).
fn dsc_id(name: &str, scope: &str) -> String {
    let sanitised: String = name
        .chars()
        .map(|c| if c.is_alphanumeric() { c } else { '_' })
        .collect();
    format!("{}_{}", scope, sanitised)
}

fn reg_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn reg_unescape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\\' {
            match chars.next() {
                Some('\\') => out.push('\\'),
                Some('"') => out.push('"'),
                Some('n') => out.push('\n'),
                Some(other) => {
                    out.push('\\');
                    out.push(other);
                }
                None => out.push('\\'),
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Parse JSON export back into a snapshot. Does NOT write to the registry.
pub fn parse_json(content: &str) -> Result<EnvSnapshot, EnvarlyError> {
    let v: serde_json::Value = serde_json::from_str(content)
        .map_err(|e| EnvarlyError::InvalidInput(format!("JSON parse error: {e}")))?;

    let as_map = |key: &str| -> HashMap<String, String> {
        v.get(key)
            .and_then(|o| o.as_object())
            .map(|m| {
                m.iter()
                    .filter_map(|(k, vv)| vv.as_str().map(|s| (k.clone(), s.to_owned())))
                    .collect()
            })
            .unwrap_or_default()
    };

    Ok(EnvSnapshot {
        user: as_map("user"),
        system: as_map("system"),
    })
}

/// Parse a .reg file back into a snapshot. Does NOT write to the registry.
pub fn parse_reg(content: &str) -> Result<EnvSnapshot, EnvarlyError> {
    let mut user: HashMap<String, String> = HashMap::new();
    let mut system: HashMap<String, String> = HashMap::new();
    let mut current: Option<bool> = None; // Some(true) = user env, Some(false) = system env

    for raw_line in content.lines() {
        let line = raw_line.trim_start_matches('\u{feff}').trim_end_matches('\r').trim();
        if line.is_empty() || line.starts_with(';') || line.starts_with("Windows Registry Editor") {
            continue;
        }
        if line.starts_with('[') {
            let lower = line.to_lowercase();
            if lower.contains("hkey_current_user\\environment") {
                current = Some(true);
            } else if lower.contains("session manager\\environment") {
                current = Some(false);
            } else {
                current = None;
            }
            continue;
        }
        if let Some(is_user) = current {
            if let Some((name, value)) = parse_reg_entry(line) {
                if is_user {
                    user.insert(name, value);
                } else {
                    system.insert(name, value);
                }
            }
        }
    }

    Ok(EnvSnapshot { user, system })
}

/// Parse a single `"name"="value"` registry entry line.
fn parse_reg_entry(line: &str) -> Option<(String, String)> {
    if !line.starts_with('"') {
        return None; // skip non-string values (dword, binary, etc.)
    }
    let after_open = &line[1..]; // skip leading "
    let (name_raw, after_name) = split_at_unescaped_quote(after_open)?;
    let after_eq = after_name.strip_prefix("=\"")?;
    let (value_raw, _) = split_at_unescaped_quote(after_eq)?;
    Some((reg_unescape(name_raw), reg_unescape(value_raw)))
}

/// Returns (before_quote, after_quote) split at the first unescaped `"`.
fn split_at_unescaped_quote(s: &str) -> Option<(&str, &str)> {
    let mut escaped = false;
    for (i, c) in s.char_indices() {
        if escaped {
            escaped = false;
        } else if c == '\\' {
            escaped = true;
        } else if c == '"' {
            return Some((&s[..i], &s[i + 1..]));
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture() -> EnvSnapshot {
        EnvSnapshot {
            user: [
                ("PATH".to_string(), "C:\\bin;C:\\tools".to_string()),
                ("JAVA_HOME".to_string(), "C:\\jdk21".to_string()),
            ]
            .into(),
            system: [
                ("WINDIR".to_string(), "C:\\Windows".to_string()),
                ("OS".to_string(), "Windows_NT".to_string()),
            ]
            .into(),
        }
    }

    // ── JSON ──────────────────────────────────────────────────────────────

    #[test]
    fn json_roundtrip_all() {
        let snap = fixture();
        let json = to_json(&snap, "All");
        let parsed = parse_json(&json).unwrap();
        assert_eq!(parsed.user, snap.user);
        assert_eq!(parsed.system, snap.system);
    }

    #[test]
    fn json_roundtrip_user_only() {
        let snap = fixture();
        let parsed = parse_json(&to_json(&snap, "User")).unwrap();
        assert_eq!(parsed.user, snap.user);
        assert!(parsed.system.is_empty());
    }

    #[test]
    fn json_roundtrip_system_only() {
        let snap = fixture();
        let parsed = parse_json(&to_json(&snap, "System")).unwrap();
        assert!(parsed.user.is_empty());
        assert_eq!(parsed.system, snap.system);
    }

    #[test]
    fn json_invalid_returns_error() {
        assert!(parse_json("not json at all").is_err());
    }

    #[test]
    fn json_missing_sections_gives_empty_maps() {
        let parsed = parse_json("{}").unwrap();
        assert!(parsed.user.is_empty());
        assert!(parsed.system.is_empty());
    }

    // ── REG ───────────────────────────────────────────────────────────────

    #[test]
    fn reg_roundtrip_all() {
        let snap = fixture();
        let parsed = parse_reg(&to_reg(&snap, "All")).unwrap();
        assert_eq!(parsed.user, snap.user);
        assert_eq!(parsed.system, snap.system);
    }

    #[test]
    fn reg_roundtrip_user_only() {
        let snap = fixture();
        let parsed = parse_reg(&to_reg(&snap, "User")).unwrap();
        assert_eq!(parsed.user, snap.user);
        assert!(parsed.system.is_empty());
    }

    #[test]
    fn reg_escape_backslash_roundtrip() {
        let snap = EnvSnapshot {
            user: [("X".to_string(), "C:\\foo\\bar".to_string())].into(),
            system: Default::default(),
        };
        let parsed = parse_reg(&to_reg(&snap, "User")).unwrap();
        assert_eq!(parsed.user["X"], "C:\\foo\\bar");
    }

    #[test]
    fn reg_escape_quote_roundtrip() {
        let snap = EnvSnapshot {
            user: [("X".to_string(), r#"say "hello""#.to_string())].into(),
            system: Default::default(),
        };
        let parsed = parse_reg(&to_reg(&snap, "User")).unwrap();
        assert_eq!(parsed.user["X"], r#"say "hello""#);
    }

    #[test]
    fn reg_ignores_unrelated_sections() {
        let content = "Windows Registry Editor Version 5.00\r\n\
                       \r\n[HKEY_LOCAL_MACHINE\\SOFTWARE\\SomeApp]\r\n\
                       \"key\"=\"value\"\r\n";
        let parsed = parse_reg(content).unwrap();
        assert!(parsed.user.is_empty());
        assert!(parsed.system.is_empty());
    }

    #[test]
    fn reg_skips_non_string_values() {
        let content = "Windows Registry Editor Version 5.00\r\n\
                       \r\n[HKEY_CURRENT_USER\\Environment]\r\n\
                       \"PATH\"=\"C:\\\\bin\"\r\n\
                       \"DWORD_VAL\"=dword:00000001\r\n";
        let parsed = parse_reg(content).unwrap();
        assert_eq!(parsed.user["PATH"], "C:\\bin");
        assert!(!parsed.user.contains_key("DWORD_VAL"));
    }

    // ── IaC helpers ───────────────────────────────────────────────────────

    #[test]
    fn ps1_quote_simple() {
        assert_eq!(ps1_quote("hello"), "'hello'");
    }

    #[test]
    fn ps1_quote_with_single_quote() {
        assert_eq!(ps1_quote("it's"), "'it''s'");
    }

    #[test]
    fn ps1_quote_backslash_unchanged() {
        // Backslashes don't need escaping in single-quoted PS strings
        assert_eq!(ps1_quote("C:\\foo"), "'C:\\foo'");
    }

    #[test]
    fn yaml_quote_simple() {
        assert_eq!(yaml_quote("hello"), "\"hello\"");
    }

    #[test]
    fn yaml_quote_backslash() {
        assert_eq!(yaml_quote("C:\\foo"), "\"C:\\\\foo\"");
    }

    #[test]
    fn yaml_quote_double_quote() {
        assert_eq!(yaml_quote(r#"say "hi""#), r#""say \"hi\"""#);
    }

    #[test]
    fn dsc_id_sanitises() {
        assert_eq!(dsc_id("MY-VAR", "User"), "User_MY_VAR");
    }

    // ── IaC generators ────────────────────────────────────────────────────

    #[test]
    fn ps1_contains_set_env_calls() {
        let snap = fixture();
        let out = to_ps1(&snap, "All");
        assert!(out.contains("[Environment]::SetEnvironmentVariable('PATH'"));
        assert!(out.contains("'User'"));
        assert!(out.contains("[Environment]::SetEnvironmentVariable('WINDIR'"));
        assert!(out.contains("'Machine'"));
    }

    #[test]
    fn ps1_user_scope_omits_system() {
        let snap = fixture();
        let out = to_ps1(&snap, "User");
        assert!(out.contains("'User'"));
        assert!(!out.contains("'Machine'"));
    }

    #[test]
    fn dsc_v2_contains_configuration_block() {
        let snap = fixture();
        let out = to_dsc_v2(&snap, "All");
        assert!(out.contains("Configuration EnvarlyConfig"));
        assert!(out.contains("Import-DscResource -ModuleName PSDscResources"));
        assert!(out.contains("Environment User_PATH"));
        assert!(out.contains("Target = @('User')"));
        assert!(out.contains("Target = @('Machine')"));
    }

    #[test]
    fn dsc_v3_contains_schema_and_resources() {
        let snap = fixture();
        let out = to_dsc_v3(&snap, "All");
        assert!(out.contains("$schema: https://aka.ms/DSC/2023/08/config"));
        assert!(out.contains("type: Microsoft.Windows/Environment"));
        assert!(out.contains("scope: CurrentUser"));
        assert!(out.contains("scope: LocalMachine"));
    }

    #[test]
    fn ansible_contains_win_environment() {
        let snap = fixture();
        let out = to_ansible(&snap, "All");
        assert!(out.contains("ansible.windows.win_environment:"));
        assert!(out.contains("level: user"));
        assert!(out.contains("level: machine"));
        assert!(out.contains("state: present"));
    }

    #[test]
    fn ansible_system_scope_omits_user() {
        let snap = fixture();
        let out = to_ansible(&snap, "System");
        assert!(!out.contains("level: user"));
        assert!(out.contains("level: machine"));
    }
}
